### ISSUE TITLE
Collection of Java error messages

### ISSUE THREAD

**Issue by vadi2** [health-validator/Hammer#362]
Running the Java validation as an external process comes with its own set of error messages, not all of which are particularly user-friendly. This issue aims to keep track of them so they can be translated to something that makes more sense.

| Message | Handled by Hammer |
|-|-|
| `Error: Unable to access jarfile <path>\org.hl7.fhir.validator.jar` | no |

**Comment by vadi2** [comment]
| Severity | Text                                                                                                                                                                                                                                                                                                                                   | Location |
| -------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------- |
| error    | FHIR Validation tool Version 5.3.12-SNAPSHOT (Git# 9a82457b36c6). Built 2021-05-07T18:52:19.697Z (13 days old)                                                                                                                                                                                                                         |          |
| error    |   Java:   14.0.2 from /usr/lib/jvm/java-14-openjdk-amd64 on amd64 (64bit). 8030MB available                                                                                                                                                                                                                                            |          |
| error    |   Paths:  Current = /media/vadi/SSDer/Programs/Hammer, Package Cache = /home/vadi/.fhir/packages                                                                                                                                                                                                                                       |          |
| error    |   Params: -version 3.0 -tx https://tx.fhir.org/r3 -ig /media/vadi/SSDer/Programs/Hammer/bin/Debug/net5.0/assets/examples -output /tmp/tmpuFoRzY.tmp.json /tmp/tmpqHTyxZ.tmp.json                                                                                                                                                       |          |
| error    | Loading                                                                                                                                                                                                                                                                                                                                |          |
| error    |   Load FHIR v3.0 from hl7.fhir.r3.core#3.0.2 - 4017 resources (00:01.0822)                                                                                                                                                                                                                                                             |          |
| error    |   Load hl7.terminology#2.1.0 - 3767 resources (00:00.0537)                                                                                                                                                                                                                                                                             |          |
| error    |   Terminology server https://tx.fhir.org/r3Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to connect to terminology server. Use parameter '-tx n/a' to run without using terminology services to validate LOINC, SNOMED, ICD-X etc. Error = Error sending Http Request: Connect to tx.fhir.org:443 timed out |          |
| error    | 	at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:302)                                                                                                                                                                                                                                        |          |
| error    | 	at org.hl7.fhir.validation.ValidationEngine.connectToTSServer(ValidationEngine.java:261)                                                                                                                                                                                                                                              |          |
| error    | 	at org.hl7.fhir.validation.ValidationEngine.setTerminologyServer(ValidationEngine.java:640)                                                                                                                                                                                                                                           |          |
| error    | 	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:230)                                                                                                                                                                                                                             |          |
| error    | 	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:212)                                                                                                                                                                                                                             |          |
| error    | 	at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:203)                                                                                                                                                                                                                                                           |          |
| error    | 	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:159)                                                                                                                                                                                                                                                                   |          |
| error    | Caused by: org.hl7.fhir.dstu3.utils.client.EFhirClientException: Error sending Http Request: Connect to tx.fhir.org:443 timed out                                                                                                                                                                                                      |          |
| error    | 	at org.hl7.fhir.dstu3.utils.client.ClientUtils.sendRequest(ClientUtils.java:352)                                                                                                                                                                                                                                                      |          |
| error    | 	at org.hl7.fhir.dstu3.utils.client.ClientUtils.issueResourceRequest(ClientUtils.java:240)                                                                                                                                                                                                                                             |          |
| error    | 	at org.hl7.fhir.dstu3.utils.client.ClientUtils.issueResourceRequest(ClientUtils.java:224)                                                                                                                                                                                                                                             |          |
| error    | 	at org.hl7.fhir.dstu3.utils.client.ClientUtils.issueResourceRequest(ClientUtils.java:215)                                                                                                                                                                                                                                             |          |
| error    | 	at org.hl7.fhir.dstu3.utils.client.ClientUtils.issueGetResourceRequest(ClientUtils.java:151)                                                                                                                                                                                                                                          |          |
| error    | 	at org.hl7.fhir.dstu3.utils.client.FHIRToolingClient.getTerminologyCapabilities(FHIRToolingClient.java:834)                                                                                                                                                                                                                           |          |
| error    | 	at org.hl7.fhir.convertors.txClient.TerminologyClientR3.getTerminologyCapabilities(TerminologyClientR3.java:63)                                                                                                                                                                                                                       |          |
| error    | 	at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:299)                                                                                                                                                                                                                                        |          |
| error    | 	... 6 more                                                                                                                                                                                                                                                                                                                            |          |
| error    | Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to tx.fhir.org:443 timed out                                                                                                                                                                                                                                          |          |
| error    | 	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:545)                                                                                                                                                                                                                                                 |          |
| error    | 	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:415)                                                                                                                                                                                                                                                 |          |
| error    | 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)                                                                                                                                                                                                                 |          |
| error    | 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)                                                                                                                                                                                                                                   |          |
| error    | 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605)                                                                                                                                                                                                                                     |          |
| error    | 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)                                                                                                                                                                                                                                        |          |
| error    | 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)                                                                                                                                                                                                                                              |          |
| error    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)                                                                                                                                                                                                                                               |          |
| error    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)                                                                                                                                                                                                                                              |          |
| error    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)                                                                                                                                                                                                                                               |          |
| error    | 	at org.hl7.fhir.dstu3.utils.client.ClientUtils.sendRequest(ClientUtils.java:347)                                                                                                                                                                                                                                                      |          |
| error    | 	... 13 more                                                                                                                                                                                                                                                                                                                           |          |
